Add function_arguments_typed to return alloy Vec<DynSolType>
cdump/evmole pull request #4
Opened 2024-07-04 16:24 UTC by wtdcode

As title, this adds a new function `function_arguments_typed` to return `Vec<DynSolType>`, which makes it much easier to use because parsing string returned by `function_arguments` is really a pain.

I ran the benchmark locally, and I didn't notice obvious performance regression. I compared the new implementation against `evmole-py` and the errors seem unrelated to this PR. For instance, most errors in `largest1k` is mismatching between `string` and `bytes` but the rust implementation seems not to return `string` anywhere.

2024-07-06 20:23 UTC, cdump commented
Thanks for PR, I like the idea and will take a look after the EthCC week (after 15 July)

2024-07-15 08:42 UTC, cdump requested changes

2024-07-15 08:42 UTC, cdump commented on rust/src/arguments.rs
> +        .join(",")
I want to keep external deps as minimal as possible now, so I suggest using this variant instead of "itertools":
```rust
  .map(|t| t.sol_type_name().to_string())
  .collect::<Vec<String>>()
  .join(",")
```
We'll have additional allocation, but we can accept that.

2024-07-15 08:42 UTC, cdump commented on rust/Cargo.toml
> +alloy = {version = "0.1", features = ["full"]}
1. We need only `alloy-dyn-abi = {version = "0.7.7" }`, not the full `alloy` package
2. `itertools` is not required, see the review comment below

2024-07-15 08:42 UTC, cdump commented on rust/src/arguments.rs
> -          StepResult{op: op::AND, fa: Some(Element{label: Some(Label::Arg(Val{offset, path, add_val, and_mask: None})), ..}), sa: Some(ot), ..}
nit: I find that the old format for match looks better, but I was unable to configure rust-fmt to keep only that part untouched. So it's okay; I'll probably revert this part by hand after merging or think about another way to configure rust-fmt properly.

2024-07-15 08:42 UTC, cdump commented on rust/src/arguments.rs
> +    trace!(
I don't like this change.
These log messages are not intended to be used by library users; they're just for me (and other developers who need to debug evmole internals).
Logging from libraries is quite a controversial issue in itself, which I think should be used very carefully and with at least providing more context about the log message origin. But in this case, I'm sure it will be better to stick with the old `feature=trace` and `println!`.

2024-07-15 08:42 UTC, cdump commented on rust/src/lib.rs
> +pub use arguments::function_arguments_typed;
What do you think about `function_arguments_alloy`?

2024-07-15 08:42 UTC, cdump commented on rust/src/arguments.rs
> +                if q.len() == 1 {
Maybe 
```rust
                vec![DynSolType::Array(Box::new(
                    if q.len() == 1 {
                        q[0].clone()
                    } else {
                        DynSolType::Tuple(q)
                    }
                ))]
```

2024-07-15 08:42 UTC, cdump commented on rust/src/arguments.rs
> +            .flatten()
From rust clippy:
```
warning: called `map(..).flatten()` on `Iterator`
  --> src/arguments.rs:89:14
   |
89 |               .map(|k| {
   |  ______________^
90 | |                 self.children
91 | |                     .get(&k)
92 | |                     .map_or(vec![DynSolType::Uint(256)], |val| val.to_alloy_type(false))
93 | |                     .into_iter()
94 | |             })
95 | |             .flatten()
   | |______________________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten
   = note: `#[warn(clippy::map_flatten)]` on by default
help: try replacing `map` with `flat_map` and remove the `.flatten()`
   |
89 ~             .flat_map(|k| {
90 +                 self.children
91 +                     .get(&k)
92 +                     .map_or(vec![DynSolType::Uint(256)], |val| val.to_alloy_type(false))
93 +                     .into_iter()
94 +             })
```

2024-07-16 08:15 UTC, wtdcode commented on rust/src/evm/vm.rs
> +                    let (from_code_length, _) = if src_off + size < code_len {
1. I can't remember exactly the reason because I was fixing this in a midnight to solve `evmole` crashing with a random unverified contract. Anyway, you are right, it can be simplified.
2. This one is shorter but harder to understand and maintain. I would like to leave it clearly and explicitly so that the thing in point 1 above won't happen next time =).

2024-07-16 08:16 UTC, wtdcode commented on rust/src/lib.rs
> +pub use arguments::function_arguments_typed;
okay.

2024-07-16 08:17 UTC, wtdcode commented on rust/Cargo.toml
> +alloy = {version = "0.1", features = ["full"]}
Sure, just my bad habits when playing with the code.

2024-07-16 08:18 UTC, wtdcode commented on rust/src/arguments.rs
> +        .join(",")
okay, though I think rustc should be smart enough to optimize this.

2024-07-16 08:19 UTC, wtdcode commented on rust/src/arguments.rs
> +    trace!(
Okay. I can understand it's different taste and I'm neutral with it. Will revert to previous `trace` feature.

2024-07-16 08:19 UTC, wtdcode commented on rust/src/arguments.rs
> +            .flatten()
Didn't notice this, will fix.

2024-07-16 08:20 UTC, wtdcode commented on rust/src/arguments.rs
> +                if q.len() == 1 {
okay.

2024-07-16 08:53 UTC, cdump commented on rust/src/lib.rs
> +pub use arguments::function_arguments_typed;
If you are okay with both variants, let me think for some time about `_typed` vs `_alloy`, just want to make sure that we will choose the best option for public API

2024-07-16 08:56 UTC, cdump commented on rust/src/evm/vm.rs
> +                    let (from_code_length, _) = if src_off + size < code_len {
Let's review it again after (1) simplification; it will probably really be much easier to read and understand

2024-07-16 12:22 UTC, cdump commented on rust/src/lib.rs
> +pub use arguments::function_arguments_typed;
I think `function_arguments_alloy` is better

2024-07-25 11:14 UTC, cdump commented on rust/src/evm/vm.rs
> +                    let (from_code_length, _) = if src_off + size < code_len {
I've pushed `if src_off < code_len {` to the master branch just to make master work while we are here. Feel free to rewrite it according to your proposal if you want.

2024-08-24 05:31 UTC, cdump commented
> parsing string returned by function_arguments is really a pain

Wrapping the result in `()` and extracting `Vec<DynSolType>` from results looks not so ugly:
```rust

use  alloy_dyn_abi::DynSolType;

fn main() {
    let code = hex::decode("6080604052348015600e575f80fd5b50600436106030575f3560e01c80632125b65b146034578063b69ef8a8146044575b5f80fd5b6044603f3660046046565b505050565b005b5f805f606084860312156057575f80fd5b833563ffffffff811681146069575f80fd5b925060208401356001600160a01b03811681146083575f80fd5b915060408401356001600160e01b0381168114609d575f80fd5b80915050925092509256").unwrap();

    let a = evmole::function_arguments(&code, &[0x21, 0x25, 0xb6, 0x5b], 0);
    println!("{}", a);

    if let Ok(DynSolType::Tuple(v)) = DynSolType::parse(&format!("({})", &a)) {
        println!("{:?}", v); // type = Vec<DynSolType>
    }
}
```

2024-08-24 05:33 UTC, wtdcode commented
> > parsing string returned by function_arguments is really a pain
> 
> Wrapping the result in `()` and extracting `Vec<DynSolType>` from results looks not so ugly:
> 
> ```rust
> use  alloy_dyn_abi::DynSolType;
> 
> fn main() {
>     let code = hex::decode("6080604052348015600e575f80fd5b50600436106030575f3560e01c80632125b65b146034578063b69ef8a8146044575b5f80fd5b6044603f3660046046565b505050565b005b5f805f606084860312156057575f80fd5b833563ffffffff811681146069575f80fd5b925060208401356001600160a01b03811681146083575f80fd5b915060408401356001600160e01b0381168114609d575f80fd5b80915050925092509256").unwrap();
> 
>     let a = evmole::function_arguments(&code, &[0x21, 0x25, 0xb6, 0x5b], 0);
>     println!("{}", a);
> 
>     if let Ok(DynSolType::Tuple(v)) = DynSolType::parse(&format!("({})", &a)) {
>         println!("{:?}", v); // type = Vec<DynSolType>
>     }
> }
> ```
> 
>  ```
> uint32,address,uint224
> [Uint(32), Address, Uint(224)]
> ```

This doesn’t work for certain types string returned by evmole.

2024-08-24 05:49 UTC, cdump commented
Do you have any examples? This is probably a bug inside evmole that I need to fix independently of this PR

2024-08-24 05:51 UTC, wtdcode commented
> Do you have any examples? This is probably a bug inside evmole that I need to fix independently of this PR

This is generally related to the nested types, where the string returned by evmole is not accepted by alloy, though the abi is correct by my manual checking. I don't have exact example for that because this happens pretty frequently when I decoded more than 50M onchain contracts across various evm-compatible chains.

2024-08-24 06:03 UTC, wtdcode commented
I have resolved the conflicts and updated according to reviews. I just forgot this PR =).

2024-08-24 06:09 UTC, wtdcode commented
Also add a testcase for previous crashing bytecode.

2024-08-24 08:07 UTC, cdump commented
>  the string returned by evmole is not accepted by alloy

I've tested it on all mainnet contracts and didn't find any errors; that's strange.

2024-08-24 08:08 UTC, cdump commented
Merged to master with reverting some code-format changes: https://github.com/cdump/evmole/commit/2ee8495e2ca9a4e5f783379b85f48efc1a7f9245

2024-08-24 08:09 UTC, closed without merging

2024-08-24 08:12 UTC, wtdcode commented
> > the string returned by evmole is not accepted by alloy
> 
> I've tested it on all mainnet contracts and didn't find any errors; that's strange.

I would assume it's due to some updates, either alloy or emvole? I notice this breakage after one `cargo update`. But anyway, thanks for merging this =).

2024-08-24 08:13 UTC, wtdcode commented
> Merged to master with reverting some code-format changes: [2ee8495](https://github.com/cdump/evmole/commit/2ee8495e2ca9a4e5f783379b85f48efc1a7f9245)

You may want a custom rustfmt style? I just run `cargo fmt` automatically.

2024-08-24 08:17 UTC, cdump commented
> due to some updates, either alloy or emvole
maybe, but anyway function returning Vec<DynSolType> is better

> want a custom rustfmt style
I just don't like rustfmt's style for match cases; I find the current version more readable. For other parts, rustfmt is okay. Contributors should use it by default, and I will either roll back the match-case style, find another way to configure it, or convince myself that rustfmt's style is also acceptable.

Thanks for PR :)